#include <linux/device/pci_ids.h>

#define PCI_ID_NAME(id, str)   { .class = id, .name = str }

pci_ids_s pci_idnames[] = {
    // PCI_BASE_CLASS_STORAGE
    PCI_ID_NAME(PCI_CLASS_STORAGE_SCSI, "SCSI"),
    PCI_ID_NAME(PCI_CLASS_STORAGE_IDE, "IDE"),
    PCI_ID_NAME(PCI_CLASS_STORAGE_FLOPPY, "FLOPPY"),
    PCI_ID_NAME(PCI_CLASS_STORAGE_IPI, "IPI"),
    PCI_ID_NAME(PCI_CLASS_STORAGE_RAID, "RAID"),
    PCI_ID_NAME(PCI_CLASS_STORAGE_SATA, "SATA"),
    PCI_ID_NAME(PCI_CLASS_STORAGE_SATA_AHCI, "SATA_AHCI"),
    PCI_ID_NAME(PCI_CLASS_STORAGE_SAS, "SAS"),
    PCI_ID_NAME(PCI_CLASS_STORAGE_NVM_IO, "NVM IO"),
    PCI_ID_NAME(PCI_CLASS_STORAGE_NVM_ADMIN, "NVM Admin"),
    PCI_ID_NAME(PCI_CLASS_STORAGE_OTHER, "Other Storage"),

    // PCI_BASE_CLASS_NETWORK
    PCI_ID_NAME(PCI_CLASS_NETWORK_ETHERNET, "Ethernet"),
    PCI_ID_NAME(PCI_CLASS_NETWORK_TOKEN_RING, "Token Ring"),
    PCI_ID_NAME(PCI_CLASS_NETWORK_FDDI, "FDDI"),
    PCI_ID_NAME(PCI_CLASS_NETWORK_ATM, "ATM"),
    PCI_ID_NAME(PCI_CLASS_NETWORK_OTHER, "Other Network"),

    // PCI_BASE_CLASS_DISPLAY
    PCI_ID_NAME(PCI_CLASS_DISPLAY_VGA, "VGA"),
    PCI_ID_NAME(PCI_CLASS_DISPLAY_XGA, "XGA"),
    PCI_ID_NAME(PCI_CLASS_DISPLAY_3D, "3D"),
    PCI_ID_NAME(PCI_CLASS_DISPLAY_OTHER, "Other Display"),

    // PCI_BASE_CLASS_MULTIMEDIA
    PCI_ID_NAME(PCI_CLASS_MULTIMEDIA_VIDEO, "Video"),
    PCI_ID_NAME(PCI_CLASS_MULTIMEDIA_AUDIO, "Audio"),
    PCI_ID_NAME(PCI_CLASS_MULTIMEDIA_PHONE, "Phone"),
    PCI_ID_NAME(PCI_CLASS_MULTIMEDIA_HD_AUDIO, "HD Audio"),
    PCI_ID_NAME(PCI_CLASS_MULTIMEDIA_OTHER, "Other Multimedia"),

    // PCI_BASE_CLASS_MEMORY
    PCI_ID_NAME(PCI_CLASS_MEMORY_RAM, "RAM"),
    PCI_ID_NAME(PCI_CLASS_MEMORY_FLASH, "Flash"),
    PCI_ID_NAME(PCI_CLASS_MEMORY_CXL, "CXL"),
    PCI_ID_NAME(PCI_CLASS_MEMORY_OTHER, "Other Memory"),

    // PCI_BASE_CLASS_BRIDGE
    PCI_ID_NAME(PCI_CLASS_BRIDGE_HOST, "Host"),
    PCI_ID_NAME(PCI_CLASS_BRIDGE_ISA, "ISA"),
    PCI_ID_NAME(PCI_CLASS_BRIDGE_EISA, "EISA"),
    PCI_ID_NAME(PCI_CLASS_BRIDGE_MC, "MC"),
    PCI_ID_NAME(PCI_CLASS_BRIDGE_PCI, "PCI"),
    PCI_ID_NAME(PCI_CLASS_BRIDGE_PCMCIA, "PCMCIA"),
    PCI_ID_NAME(PCI_CLASS_BRIDGE_NUBUS, "NUBUS"),
    PCI_ID_NAME(PCI_CLASS_BRIDGE_CARDBUS, "CARDBUS"),
    PCI_ID_NAME(PCI_CLASS_BRIDGE_RACEWAY, "RACEWAY"),
    PCI_ID_NAME(PCI_CLASS_BRIDGE_OTHER, "Other Bridge"),

    // PCI_BASE_CLASS_COMMUNICATION
    PCI_ID_NAME(PCI_CLASS_COMMUNICATION_SERIAL, "Serial"),
    PCI_ID_NAME(PCI_CLASS_COMMUNICATION_PARALLEL, "Parallel"),
    PCI_ID_NAME(PCI_CLASS_COMMUNICATION_MULTISERIAL, "Multi-Serial"),
    PCI_ID_NAME(PCI_CLASS_COMMUNICATION_MODEM, "Modem"),
    PCI_ID_NAME(PCI_CLASS_COMMUNICATION_OTHER, "Other Communication"),

    // PCI_BASE_CLASS_SYSTEM
    PCI_ID_NAME(PCI_CLASS_SYSTEM_PIC, "PIC"),
    PCI_ID_NAME(PCI_CLASS_SYSTEM_PIC_IOAPIC, "IOAPIC"),
    PCI_ID_NAME(PCI_CLASS_SYSTEM_PIC_IOXAPIC, "IOXAPIC"),
    PCI_ID_NAME(PCI_CLASS_SYSTEM_DMA, "DMA"),
    PCI_ID_NAME(PCI_CLASS_SYSTEM_TIMER, "Timer"),
    PCI_ID_NAME(PCI_CLASS_SYSTEM_RTC, "RTC"),
    PCI_ID_NAME(PCI_CLASS_SYSTEM_PCI_HOTPLUG, "PCI Hot-Plug"),
    PCI_ID_NAME(PCI_CLASS_SYSTEM_SDHCI, "SDHCI"),
    PCI_ID_NAME(PCI_CLASS_SYSTEM_RCEC, "RCEC"),
    PCI_ID_NAME(PCI_CLASS_SYSTEM_OTHER, "Other System"),

    // PCI_BASE_CLASS_INPUT
    PCI_ID_NAME(PCI_CLASS_INPUT_KEYBOARD, "Keyboard"),
    PCI_ID_NAME(PCI_CLASS_INPUT_PEN, "Pen"),
    PCI_ID_NAME(PCI_CLASS_INPUT_MOUSE, "Mouse"),
    PCI_ID_NAME(PCI_CLASS_INPUT_SCANNER, "Scanner"),
    PCI_ID_NAME(PCI_CLASS_INPUT_GAMEPORT, "Gameport"),
    PCI_ID_NAME(PCI_CLASS_INPUT_OTHER, "Other Input"),

    // PCI_BASE_CLASS_DOCKING
    PCI_ID_NAME(PCI_CLASS_DOCKING_GENERIC, "Generic"),
    PCI_ID_NAME(PCI_CLASS_DOCKING_OTHER, "Other Docking"),

    // PCI_BASE_CLASS_PROCESSOR
    PCI_ID_NAME(PCI_CLASS_PROCESSOR_386, "386"),
    PCI_ID_NAME(PCI_CLASS_PROCESSOR_486, "486"),
    PCI_ID_NAME(PCI_CLASS_PROCESSOR_PENTIUM, "Pentium"),
    PCI_ID_NAME(PCI_CLASS_PROCESSOR_ALPHA, "Alpha"),
    PCI_ID_NAME(PCI_CLASS_PROCESSOR_POWERPC, "PowerPC"),
    PCI_ID_NAME(PCI_CLASS_PROCESSOR_MIPS, "MIPS"),
    PCI_ID_NAME(PCI_CLASS_PROCESSOR_CO, "Co-Processor"),

    // PCI_BASE_CLASS_SERIAL
    PCI_ID_NAME(PCI_CLASS_SERIAL_FIREWIRE, "FireWire"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_FIREWIRE_OHCI, "FireWire OHCI"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_ACCESS, "Access"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_SSA, "SSA"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_USB, "USB"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_USB_UHCI, "USB UHCI"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_USB_OHCI, "USB OHCI"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_USB_EHCI, "USB EHCI"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_USB_XHCI, "USB XHCI"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_USB_DEVICE, "USB Device"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_FIBER, "Fiber"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_SMBUS, "SMBus"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_IPMI, "IPMI"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_IPMI_SMIC, "IPMI SMIC"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_IPMI_KCS, "IPMI KCS"),
    PCI_ID_NAME(PCI_CLASS_SERIAL_IPMI_BT, "IPMI BT"),

    // PCI_BASE_CLASS_WIRELESS
    PCI_ID_NAME(PCI_CLASS_WIRELESS_RF_CONTROLLER, "RF Controller"),
    PCI_ID_NAME(PCI_CLASS_WIRELESS_WHCI, "WLAN"),

    // PCI_BASE_CLASS_INTELLIGENT
    PCI_ID_NAME(PCI_CLASS_INTELLIGENT_I2O, "I2O"),

    // PCI_BASE_CLASS_SATELLITE
    PCI_ID_NAME(PCI_CLASS_SATELLITE_TV, "TV"),
    PCI_ID_NAME(PCI_CLASS_SATELLITE_AUDIO, "Audio"),
    PCI_ID_NAME(PCI_CLASS_SATELLITE_VOICE, "Voice"),
    PCI_ID_NAME(PCI_CLASS_SATELLITE_DATA, "Data"),

    // PCI_BASE_CLASS_CRYPT
    PCI_ID_NAME(PCI_CLASS_CRYPT_NETWORK, "Network"),
    PCI_ID_NAME(PCI_CLASS_CRYPT_ENTERTAINMENT, "Entertainment"),
    PCI_ID_NAME(PCI_CLASS_CRYPT_OTHER, "Other Cryptographic"),

    // PCI_BASE_CLASS_SIGNAL_PROCESSING
    PCI_ID_NAME(PCI_CLASS_SP_DPIO, "DPIO"),
    PCI_ID_NAME(PCI_CLASS_SP_OTHER, "Other Signal Processing"),



    // Undefined CLASS, and END_OF_LIST
    PCI_ID_NAME(0xFFFFFF, "Undefined"),
};