#ifndef _MMFAULT_CONST_H_
#define _MMFAULT_CONST_H_

	#define VM_FAULT_ERROR (VM_FAULT_OOM | VM_FAULT_SIGBUS |       \
							VM_FAULT_SIGSEGV | VM_FAULT_HWPOISON | \
							VM_FAULT_HWPOISON_LARGE | VM_FAULT_FALLBACK)

#endif /* _MMFAULT_CONST_H_ */