#ifndef _LINUX_PGALLOC_CONST_H_
#define _LINUX_PGALLOC_CONST_H_


	#define GFP_PGTABLE_KERNEL	(GFP_KERNEL | __GFP_ZERO)
	#define GFP_PGTABLE_USER	(GFP_PGTABLE_KERNEL | __GFP_ACCOUNT)

#endif /* _LINUX_PGALLOC_CONST_H_ */